# multi-variable linear regression을 TensorFlow에서 구현하기2

In [1]:
import tensorflow as tf

Matrix를 이용해 구현

In [2]:
x_data = [[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

In [3]:
X = tf.placeholder(tf.float32, shape=[None, 3]) # variable의 개수에따라 shape를 설정(3)
                                                # None으로 설정한 부분은 현재는 5개의 element를 가지지만 추가할수 있기 때문에 
                                                # None으로 설정한다.
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [4]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
hypothesis = tf.matmul(X, W)+b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [6]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [8]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  23145.695 
Prediction:
 [[14.719242]
 [23.26315 ]
 [19.762218]
 [25.036617]
 [16.226238]]
10 Cost:  4.1097274 
Prediction:
 [[149.29158]
 [185.00783]
 [179.13272]
 [198.58606]
 [139.59726]]
20 Cost:  3.8960373 
Prediction:
 [[149.69945]
 [185.49684]
 [179.61528]
 [199.1105 ]
 [139.97083]]
30 Cost:  3.894197 
Prediction:
 [[149.70137]
 [185.49794]
 [179.61705]
 [199.1114 ]
 [139.97223]]
40 Cost:  3.8923614 
Prediction:
 [[149.70206]
 [185.49756]
 [179.61739]
 [199.11072]
 [139.9725 ]]
50 Cost:  3.8905258 
Prediction:
 [[149.70274]
 [185.49718]
 [179.61772]
 [199.11003]
 [139.97278]]
60 Cost:  3.8886962 
Prediction:
 [[149.70345]
 [185.4968 ]
 [179.61806]
 [199.10936]
 [139.97305]]
70 Cost:  3.8868644 
Prediction:
 [[149.70413]
 [185.49641]
 [179.61838]
 [199.10867]
 [139.97333]]
80 Cost:  3.8850236 
Prediction:
 [[149.70482]
 [185.49605]
 [179.6187 ]
 [199.10799]
 [139.97362]]
90 Cost:  3.8831887 
Prediction:
 [[149.70554]
 [185.49568]
 [179.61905]
 [199.10733]
 [139.9739 ]]
10

940 Cost:  3.7313175 
Prediction:
 [[149.7612 ]
 [185.46532]
 [179.64606]
 [199.04956]
 [139.99931]]
950 Cost:  3.7295578 
Prediction:
 [[149.76183]
 [185.46498]
 [179.64636]
 [199.04887]
 [139.99963]]
960 Cost:  3.7278335 
Prediction:
 [[149.76245]
 [185.46465]
 [179.64668]
 [199.04822]
 [139.99995]]
970 Cost:  3.726075 
Prediction:
 [[149.76308]
 [185.46431]
 [179.64699]
 [199.04753]
 [140.00027]]
980 Cost:  3.7243352 
Prediction:
 [[149.7637 ]
 [185.46397]
 [179.6473 ]
 [199.04686]
 [140.0006 ]]
990 Cost:  3.7225864 
Prediction:
 [[149.76431]
 [185.46364]
 [179.64758]
 [199.04616]
 [140.0009 ]]
1000 Cost:  3.720848 
Prediction:
 [[149.76494]
 [185.4633 ]
 [179.64789]
 [199.04549]
 [140.00122]]
1010 Cost:  3.7191017 
Prediction:
 [[149.76555]
 [185.46295]
 [179.6482 ]
 [199.0448 ]
 [140.00154]]
1020 Cost:  3.7173667 
Prediction:
 [[149.76617]
 [185.46263]
 [179.6485 ]
 [199.04413]
 [140.00186]]
1030 Cost:  3.715634 
Prediction:
 [[149.7668 ]
 [185.46231]
 [179.64883]
 [199.04347]
 [1

1970 Cost:  3.5561848 
Prediction:
 [[149.82222]
 [185.43275]
 [179.67654]
 [198.98004]
 [140.03387]]
1980 Cost:  3.5545425 
Prediction:
 [[149.82277]
 [185.43246]
 [179.67683]
 [198.97937]
 [140.03423]]
1990 Cost:  3.5528774 
Prediction:
 [[149.82335]
 [185.43216]
 [179.67712]
 [198.97871]
 [140.03459]]
2000 Cost:  3.5512378 
Prediction:
 [[149.8239 ]
 [185.43187]
 [179.6774 ]
 [198.97804]
 [140.03494]]
